INSERT INTO Property (
  title,
  description,
  price,
  type,
  status,
  listingType,
  city,
  department,
  address,
  ownerId,
  agentId,
  agencyId
) VALUES
(
  'Loft moderne avec terrasse à Paris',
  'Superbe loft de 90m² avec terrasse privée, situé au cœur du Marais. Parquet, cuisine ouverte, très lumineux.',
  890000,
  'Appartement',
  'AVAILABLE',
  'SALE',
  'Paris',
  '75',
  '12 Rue des Archives',
  6,
  1,
  1
),
(
  'Maison familiale avec jardin à Toulouse',
  'Maison de 4 chambres avec grand jardin, garage et cuisine équipée. Idéale pour une famille.',
  450000,
  'Maison',
  'AVAILABLE',
  'SALE',
  'Toulouse',
  '31',
  '18 Chemin des Écoliers',
  6,
  1,
  1
),
(
  'Studio meublé proche plage à Nice',
  'Studio de 30m² entièrement meublé, à 200m de la plage. Parfait pour étudiant ou location saisonnière.',
  950,
  'Studio',
  'AVAILABLE',
  'RENT',
  'Nice',
  '06',
  '7 Avenue Jean Médecin',
  6,
  1,
  1
),
(
  'Penthouse avec vue sur la mer à Marseille',
  'Penthouse de 120m² avec terrasse panoramique, jacuzzi et prestations haut de gamme.',
  1100000,
  'Penthouse',
  'AVAILABLE',
  'SALE',
  'Marseille',
  '13',
  '25 Boulevard Michelet',
  6,
  1,
  1
),
(
  'T2 rénové dans immeuble ancien à Lyon',
  'Appartement T2 de 60m² rénové, avec parquet, cheminée et balcon. Quartier vivant et central.',
  1250,
  'Appartement',
  'AVAILABLE',
  'RENT',
  'Lyon',
  '69',
  '3 Rue de la République',
  6,
  1,
  1
);
